language: node_js

dist: trusty

node_js:
  - '7'

before_install:
  - rvm install 2.5.1
  - gem install bundler -v 1.17.2

install:
- bundle install

before_script:
  - bundle install
  - npm install --global gulp-cli
  - npm install --save-dev gulp
  - npm install

script:
- gulp sass
- bundle exec jekyll build
#- ./_scripts/deploy.sh

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master