language: node_js
dist: trusty

node_js:
  - '7'

before_install:
  - rvm install 2.5.1
  - gem install bundler -v 1.17.2

install:
- bundle install

before_script:
  - bundle install
  - npm install --global gulp-cli
  - npm install --save-dev gulp
  - npm install

script:
- gulp build
- bundle exec jekyll build


branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache: bundler
sudo: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  #fqdn: Optional, sets a custom domain for your website, defaults to no custom domain support.
  on:
    branch: master