title: DragonPy - A Python conference
email: info@dragonpy.com
description: >- # this means to ignore newlines until "baseurl:"
  Python Best Practices for the modern Web and Data Scientists.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

collections:
  talks:
    talk: true
    output: true

# Build settings
markdown: kramdown

sass:
  style: compact
  load_paths:
    - _sass
    - node_modules/foundation-sites/scss


defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
