title: DragonPy - A Python conference
email: info@dragonpy.com
description: >-
  Python Best Practices for the modern Web and Data Scientists.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dragonpy.com" # the base hostname & protocol for your site
twitter_username: "dragonpyconf"
github_username:


# Build settings
markdown: kramdown

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

plugins:
  - jekyll-feed
