title: DragonPy - A Python conference
email: info@dragonpy.com
description: >-
  Python Best Practices for the modern Web and Data Scientists.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dragonpy.com" # the base hostname & protocol for your site
twitter_username: "dragonpyconf"
github_username:

collections:
  talks:
    talk: true
    output: true


# Build settings
markdown: kramdown

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules/foundation-sites/scss

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

plugins:
  - jekyll-feed
